language: c

dist: focal 

compiler:
  - gcc

install:
  - sudo apt-get update
  - sudo apt-get install -y python3
  - sudo apt-get install -y python3-pip
  - sudo pip install cpplint
  - sudo apt-get install -y cmake
  - sudo apt-get install -y cppcheck
  - sudo apt-get install -y gcovr
  - sudo apt-get install -y lynx
  - sudo apt-get install -y valgrind

jobs:
  include:
    - stage: "BuildCheck"
      script:
        - cmake -B build .
        - make -C build
        - cpplint --recursive --extensions=c,cpp,h --filter="-readability/casting,-legal/copyright,-build/include_what_you_use" ../*.c ../*.h ../*.cpp
        - cppcheck --inconclusive --enable=all --error-exitcode=1 --check-config -q -v --suppress=missingIncludeSystem ..

    - stage: "BuildTest"
      script:
        - cmake -B build .
        - make -C build
        - ./max_triang_test
        - gcovr -r .. --html -o report.html
        - lynx --dump ./report.html
        - valgrind --tool=memcheck --leak-check=full --leak-resolution=med --error-exitcode=1 --show-leak-kinds=all --track-origins=yes ./max_triang_test