language: c

compiler:
  - gcc

install:
  - sudo apt-get update
  - sudo apt-get install -y valgrind
  - sudo apt-get install -y libgtest-dev
  - sudo apt-get install -y cmake
  - sudo apt-get install -y cppcheck
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo cp *.a /usr/lib
  - cd -

jobs:
  include:
    - stage: "BuildCheck"
      script:
        - mkdir build
        - cd build
        - cmake ..
        - make
        - cppcheck --inconclusive --enable=all --error-exitcode=1 --check-config -q -v --suppress=missingIncludeSystem ..

    - stage: "BuildTest"
      script:
        - mkdir build
        - cd build
        - cmake ..
        - make
        - ./max_triang_test
        - valgrind --tool=memcheck --leak-check=full --leak-resolution=med --error-exitcode=1 --track-origins=yes ./max_triang_test