language: c

compiler:
  - clang

before_install:
  - sudo apt-get update
  - sudo apt-get install -y valgrind

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - valgrind --leak-check=yes ./max_triang_test